name: roadwise_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth:
  font_awesome_flutter: ^10.7.0
  http: 0.13.6
  firebase_messaging: 14.8.0
  google_maps_flutter: ^2.0.0
  cupertino_icons: ^1.0.2
  animate_do: ^3.3.3
  page_transition: ^2.1.0
  firebase_auth: ^4.17.4
  firebase_storage: ^11.2.4
  firebase_core: ^2.25.4
  flare_flutter: ^3.0.2
  image_picker: ^1.0.7
  fluttertoast: ^8.2.8
  ndialog: ^4.1.1+1
  intl: ^0.17.0
  path_provider: ^2.0.11
  cloud_firestore: ^4.17.5
  cherry_toast: ^1.9.1
  loading_animation_widget: ^1.2.1
  icons_plus: ^5.0.0
  firebase_database: ^10.5.0
  dialogflow_flutter: ^1.0.0
  rxdart: ^0.27.7
  animated_toggle_switch: ^0.8.2
  flutter_treeview: ^1.0.7+1
  panorama_viewer: ^1.0.3
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  animated_tree_view: ^2.2.1
  graphview: ^1.2.0
  org_chart: ^3.1.0
  zoom_tap_animation: ^1.1.0
  gif_view: ^0.3.1
  salomon_bottom_bar: ^3.3.2
  concentric_transition: ^1.0.3
  swipe_refresh: ^1.1.2
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/.
    - assets/icons/.
    - assets/images/.
    - assets/likes/.
    - assets/profiles/.
    - assets/icons/.
    - assets/icons/person_icon.png
    - assets/icons/user.png
    - assets/icons/user1.png
    - lib/vr/vr.jpg
    - lib/vr/vr1.jpg
    - lib/vr/vr2.jpg
    - assets/logo.gif
    - assets/onboard/onBoard1.jpg
    - assets/onboard/onBoard2.png
    - assets/onboard/onBoard3.png
  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dubai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dubai-Light.ttf
          weight: 300
        - asset: assets/fonts/Dubai-Regular.ttf
          weight: 400

    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/Orbitron-Black.ttf
          weight: 900
        - asset: assets/fonts/orbitron/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/orbitron/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/orbitron/Orbitron-Regular.ttf
          weight: 400

