name: roadwise_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth:
  http: 0.13.6
  firebase_messaging: 14.8.0
  google_maps_flutter: ^2.0.0
  animated_bottom_navigation_bar: ^1.3.3
  cupertino_icons: ^1.0.2
  animate_do: ^3.3.3
  page_transition: ^2.1.0
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.17.4
  firebase_storage: ^11.2.4
  firebase_core: ^2.25.4
  flare_flutter: ^3.0.2
  image_picker: ^1.0.7
  fluttertoast: ^8.0.9
  ndialog: ^4.1.1+1
  intl: ^0.17.0
  path_provider: ^2.0.11
  step_progress_indicator: ^1.0.2
  cloud_firestore: ^4.17.5
  cherry_toast: ^1.9.1
  loading_animation_widget: ^1.2.1
  icons_plus: ^5.0.0
  firebase_database: ^10.5.0
  dialogflow_flutter: ^1.0.0
  rxdart: ^0.27.7
  dialogflow_grpc: ^0.2.9
  sound_stream: ^0.4.1
  animated_toggle_switch: ^0.8.2
  flutter_treeview: ^1.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/.
    - assets/icons/.
    - assets/images/.
    - assets/likes/.
    - assets/profiles/.
    - assets/icons/.
    - assets/icons/home_icon.png
    - assets/icons/mail_icon.png
    - assets/icons/notifications_icon.png
    - assets/icons/person_icon.png
    - assets/icons/roadmap-planning.png
    - assets/icons/user.png
  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Bold.otf
        - asset: assets/fonts/Dubai-Light.otf
        - asset: assets/fonts/Dubai-Medium.ttf
        - asset: assets/fonts/Dubai-Regular.otf
          weight: 400
    - family: bifur
      fonts:
        - asset: assets/fonts/Dubai-Bold.otf
          weight: 400
