// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZPt_l_DrZ6YZJf6-Bxa4MIdQWPHdPSY',
    appId: '1:79663037799:web:0946e8faab63c93235c3c2',
    messagingSenderId: '79663037799',
    projectId: 'roadwise-application-54684',
    authDomain: 'roadwise-application-54684.firebaseapp.com',
    storageBucket: 'roadwise-application-54684.appspot.com',
    measurementId: 'G-9Y5VR14K04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBmz8bRTSw8_zMv5Gd4ZF8NuiNF9w_9g',
    appId: '1:79663037799:android:f2d9cd42275695d435c3c2',
    messagingSenderId: '79663037799',
    projectId: 'roadwise-application-54684',
    storageBucket: 'roadwise-application-54684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMapyiS36lLlnVEvrpfb4plDsV8fCNTAI',
    appId: '1:79663037799:ios:bc225854eda24c3f35c3c2',
    messagingSenderId: '79663037799',
    projectId: 'roadwise-application-54684',
    storageBucket: 'roadwise-application-54684.appspot.com',
    iosBundleId: 'com.roadwise.roadwiseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMapyiS36lLlnVEvrpfb4plDsV8fCNTAI',
    appId: '1:79663037799:ios:9727ee83dc941dcf35c3c2',
    messagingSenderId: '79663037799',
    projectId: 'roadwise-application-54684',
    storageBucket: 'roadwise-application-54684.appspot.com',
    iosBundleId: 'com.roadwise.roadwiseApplication.RunnerTests',
  );
}
